// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/im/zemel/proto/CommonMsgPB.proto

package com.im.zemel.protoBean;

public final class CommonMsgPBOuterClass {
  private CommonMsgPBOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.im.zemel.proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>Msg = 0;</code>
     */
    Msg(0),
    /**
     * <pre>
     * 登陆
     * </pre>
     *
     * <code>Login = 1;</code>
     */
    Login(1),
    /**
     * <pre>
     * 新好友
     * </pre>
     *
     * <code>NewFriend = 3;</code>
     */
    NewFriend(3),
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>Error = 4;</code>
     */
    Error(4),
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Ping = 5;</code>
     */
    Ping(5),
    ;

    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>Msg = 0;</code>
     */
    public static final int Msg_VALUE = 0;
    /**
     * <pre>
     * 登陆
     * </pre>
     *
     * <code>Login = 1;</code>
     */
    public static final int Login_VALUE = 1;
    /**
     * <pre>
     * 新好友
     * </pre>
     *
     * <code>NewFriend = 3;</code>
     */
    public static final int NewFriend_VALUE = 3;
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>Error = 4;</code>
     */
    public static final int Error_VALUE = 4;
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>Ping = 5;</code>
     */
    public static final int Ping_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return Msg;
        case 1: return Login;
        case 3: return NewFriend;
        case 4: return Error;
        case 5: return Ping;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.im.zemel.proto.MessageType)
  }

  public interface CommonMsgPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.im.zemel.proto.CommonMsgPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
     */
    com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType getType();

    /**
     * <pre>
     * 发件人id
     * </pre>
     *
     * <code>optional int32 fromId = 2;</code>
     */
    boolean hasFromId();
    /**
     * <pre>
     * 发件人id
     * </pre>
     *
     * <code>optional int32 fromId = 2;</code>
     */
    int getFromId();

    /**
     * <pre>
     * 收件人id
     * </pre>
     *
     * <code>optional int32 toId = 3;</code>
     */
    boolean hasToId();
    /**
     * <pre>
     * 收件人id
     * </pre>
     *
     * <code>optional int32 toId = 3;</code>
     */
    int getToId();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    boolean hasContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>optional .com.im.zemel.proto.User user = 5;</code>
     */
    boolean hasUser();
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>optional .com.im.zemel.proto.User user = 5;</code>
     */
    com.im.zemel.protoBean.CommonMsgPBOuterClass.User getUser();
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>optional .com.im.zemel.proto.User user = 5;</code>
     */
    com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder getUserOrBuilder();

    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>optional string time = 6;</code>
     */
    boolean hasTime();
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>optional string time = 6;</code>
     */
    java.lang.String getTime();
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>optional string time = 6;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <pre>
     * 消息内容(0为文字，1为图片)
     * </pre>
     *
     * <code>optional int32 contentType = 7;</code>
     */
    boolean hasContentType();
    /**
     * <pre>
     * 消息内容(0为文字，1为图片)
     * </pre>
     *
     * <code>optional int32 contentType = 7;</code>
     */
    int getContentType();
  }
  /**
   * Protobuf type {@code com.im.zemel.proto.CommonMsgPB}
   */
  public  static final class CommonMsgPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.im.zemel.proto.CommonMsgPB)
      CommonMsgPBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonMsgPB.newBuilder() to construct.
    private CommonMsgPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonMsgPB() {
      type_ = 0;
      fromId_ = 0;
      toId_ = 0;
      content_ = "";
      time_ = "";
      contentType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonMsgPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType value = com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              toId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              content_ = bs;
              break;
            }
            case 42: {
              com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.im.zemel.protoBean.CommonMsgPBOuterClass.User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              time_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              contentType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_CommonMsgPB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_CommonMsgPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.class, com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
     */
    public com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType getType() {
      @SuppressWarnings("deprecation")
      com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType result = com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType.valueOf(type_);
      return result == null ? com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType.Msg : result;
    }

    public static final int FROMID_FIELD_NUMBER = 2;
    private int fromId_;
    /**
     * <pre>
     * 发件人id
     * </pre>
     *
     * <code>optional int32 fromId = 2;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 发件人id
     * </pre>
     *
     * <code>optional int32 fromId = 2;</code>
     */
    public int getFromId() {
      return fromId_;
    }

    public static final int TOID_FIELD_NUMBER = 3;
    private int toId_;
    /**
     * <pre>
     * 收件人id
     * </pre>
     *
     * <code>optional int32 toId = 3;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 收件人id
     * </pre>
     *
     * <code>optional int32 toId = 3;</code>
     */
    public int getToId() {
      return toId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 5;
    private com.im.zemel.protoBean.CommonMsgPBOuterClass.User user_;
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>optional .com.im.zemel.proto.User user = 5;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>optional .com.im.zemel.proto.User user = 5;</code>
     */
    public com.im.zemel.protoBean.CommonMsgPBOuterClass.User getUser() {
      return user_ == null ? com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance() : user_;
    }
    /**
     * <pre>
     * 用户
     * </pre>
     *
     * <code>optional .com.im.zemel.proto.User user = 5;</code>
     */
    public com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder getUserOrBuilder() {
      return user_ == null ? com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance() : user_;
    }

    public static final int TIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object time_;
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>optional string time = 6;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>optional string time = 6;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>optional string time = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 7;
    private int contentType_;
    /**
     * <pre>
     * 消息内容(0为文字，1为图片)
     * </pre>
     *
     * <code>optional int32 contentType = 7;</code>
     */
    public boolean hasContentType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 消息内容(0为文字，1为图片)
     * </pre>
     *
     * <code>optional int32 contentType = 7;</code>
     */
    public int getContentType() {
      return contentType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, toId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getUser());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, time_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, contentType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, toId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUser());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, time_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, contentType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB)) {
        return super.equals(obj);
      }
      com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB other = (com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasFromId() == other.hasFromId());
      if (hasFromId()) {
        result = result && (getFromId()
            == other.getFromId());
      }
      result = result && (hasToId() == other.hasToId());
      if (hasToId()) {
        result = result && (getToId()
            == other.getToId());
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && getTime()
            .equals(other.getTime());
      }
      result = result && (hasContentType() == other.hasContentType());
      if (hasContentType()) {
        result = result && (getContentType()
            == other.getContentType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + getFromId();
      }
      if (hasToId()) {
        hash = (37 * hash) + TOID_FIELD_NUMBER;
        hash = (53 * hash) + getToId();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      if (hasContentType()) {
        hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContentType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.im.zemel.proto.CommonMsgPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.im.zemel.proto.CommonMsgPB)
        com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_CommonMsgPB_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_CommonMsgPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.class, com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.Builder.class);
      }

      // Construct using com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        toId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        contentType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_CommonMsgPB_descriptor;
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB getDefaultInstanceForType() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.getDefaultInstance();
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB build() {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB buildPartial() {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB result = new com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.contentType_ = contentType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB) {
          return mergeFrom((com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB other) {
        if (other == com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasFromId()) {
          setFromId(other.getFromId());
        }
        if (other.hasToId()) {
          setToId(other.getToId());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000008;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000020;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasContentType()) {
          setContentType(other.getContentType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
       */
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType getType() {
        @SuppressWarnings("deprecation")
        com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType result = com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType.valueOf(type_);
        return result == null ? com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType.Msg : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
       */
      public Builder setType(com.im.zemel.protoBean.CommonMsgPBOuterClass.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>required .com.im.zemel.proto.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int fromId_ ;
      /**
       * <pre>
       * 发件人id
       * </pre>
       *
       * <code>optional int32 fromId = 2;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 发件人id
       * </pre>
       *
       * <code>optional int32 fromId = 2;</code>
       */
      public int getFromId() {
        return fromId_;
      }
      /**
       * <pre>
       * 发件人id
       * </pre>
       *
       * <code>optional int32 fromId = 2;</code>
       */
      public Builder setFromId(int value) {
        bitField0_ |= 0x00000002;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发件人id
       * </pre>
       *
       * <code>optional int32 fromId = 2;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = 0;
        onChanged();
        return this;
      }

      private int toId_ ;
      /**
       * <pre>
       * 收件人id
       * </pre>
       *
       * <code>optional int32 toId = 3;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 收件人id
       * </pre>
       *
       * <code>optional int32 toId = 3;</code>
       */
      public int getToId() {
        return toId_;
      }
      /**
       * <pre>
       * 收件人id
       * </pre>
       *
       * <code>optional int32 toId = 3;</code>
       */
      public Builder setToId(int value) {
        bitField0_ |= 0x00000004;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 收件人id
       * </pre>
       *
       * <code>optional int32 toId = 3;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        toId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }

      private com.im.zemel.protoBean.CommonMsgPBOuterClass.User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.im.zemel.protoBean.CommonMsgPBOuterClass.User, com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder, com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder> userBuilder_;
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public Builder setUser(com.im.zemel.protoBean.CommonMsgPBOuterClass.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public Builder setUser(
          com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public Builder mergeUser(com.im.zemel.protoBean.CommonMsgPBOuterClass.User value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              user_ != null &&
              user_ != com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance()) {
            user_ =
              com.im.zemel.protoBean.CommonMsgPBOuterClass.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder getUserBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <pre>
       * 用户
       * </pre>
       *
       * <code>optional .com.im.zemel.proto.User user = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.im.zemel.protoBean.CommonMsgPBOuterClass.User, com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder, com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.im.zemel.protoBean.CommonMsgPBOuterClass.User, com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder, com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.lang.Object time_ = "";
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>optional string time = 6;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>optional string time = 6;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>optional string time = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>optional string time = 6;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>optional string time = 6;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>optional string time = 6;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        time_ = value;
        onChanged();
        return this;
      }

      private int contentType_ ;
      /**
       * <pre>
       * 消息内容(0为文字，1为图片)
       * </pre>
       *
       * <code>optional int32 contentType = 7;</code>
       */
      public boolean hasContentType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 消息内容(0为文字，1为图片)
       * </pre>
       *
       * <code>optional int32 contentType = 7;</code>
       */
      public int getContentType() {
        return contentType_;
      }
      /**
       * <pre>
       * 消息内容(0为文字，1为图片)
       * </pre>
       *
       * <code>optional int32 contentType = 7;</code>
       */
      public Builder setContentType(int value) {
        bitField0_ |= 0x00000040;
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容(0为文字，1为图片)
       * </pre>
       *
       * <code>optional int32 contentType = 7;</code>
       */
      public Builder clearContentType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        contentType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.im.zemel.proto.CommonMsgPB)
    }

    // @@protoc_insertion_point(class_scope:com.im.zemel.proto.CommonMsgPB)
    private static final com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB();
    }

    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommonMsgPB>
        PARSER = new com.google.protobuf.AbstractParser<CommonMsgPB>() {
      @java.lang.Override
      public CommonMsgPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonMsgPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonMsgPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonMsgPB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.im.zemel.protoBean.CommonMsgPBOuterClass.CommonMsgPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.im.zemel.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.im.zemel.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.im.zemel.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      uid_ = 0;
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.im.zemel.protoBean.CommonMsgPBOuterClass.User.class, com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.im.zemel.protoBean.CommonMsgPBOuterClass.User)) {
        return super.equals(obj);
      }
      com.im.zemel.protoBean.CommonMsgPBOuterClass.User other = (com.im.zemel.protoBean.CommonMsgPBOuterClass.User) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && (getUid()
            == other.getUid());
      }
      result = result && (hasPassword() == other.hasPassword());
      if (hasPassword()) {
        result = result && getPassword()
            .equals(other.getPassword());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.im.zemel.protoBean.CommonMsgPBOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.im.zemel.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.im.zemel.proto.User)
        com.im.zemel.protoBean.CommonMsgPBOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.im.zemel.protoBean.CommonMsgPBOuterClass.User.class, com.im.zemel.protoBean.CommonMsgPBOuterClass.User.Builder.class);
      }

      // Construct using com.im.zemel.protoBean.CommonMsgPBOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_User_descriptor;
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.User getDefaultInstanceForType() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.User build() {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.User buildPartial() {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.User result = new com.im.zemel.protoBean.CommonMsgPBOuterClass.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.im.zemel.protoBean.CommonMsgPBOuterClass.User) {
          return mergeFrom((com.im.zemel.protoBean.CommonMsgPBOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.im.zemel.protoBean.CommonMsgPBOuterClass.User other) {
        if (other == com.im.zemel.protoBean.CommonMsgPBOuterClass.User.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.im.zemel.protoBean.CommonMsgPBOuterClass.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int uid_ ;
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.im.zemel.proto.User)
    }

    // @@protoc_insertion_point(class_scope:com.im.zemel.proto.User)
    private static final com.im.zemel.protoBean.CommonMsgPBOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.im.zemel.protoBean.CommonMsgPBOuterClass.User();
    }

    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.im.zemel.protoBean.CommonMsgPBOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.im.zemel.proto.Body)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.im.zemel.proto.Body}
   */
  public  static final class Body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.im.zemel.proto.Body)
      BodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Body.newBuilder() to construct.
    private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Body() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_Body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.class, com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.im.zemel.protoBean.CommonMsgPBOuterClass.Body)) {
        return super.equals(obj);
      }
      com.im.zemel.protoBean.CommonMsgPBOuterClass.Body other = (com.im.zemel.protoBean.CommonMsgPBOuterClass.Body) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.im.zemel.protoBean.CommonMsgPBOuterClass.Body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.im.zemel.proto.Body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.im.zemel.proto.Body)
        com.im.zemel.protoBean.CommonMsgPBOuterClass.BodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_Body_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.class, com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.Builder.class);
      }

      // Construct using com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.internal_static_com_im_zemel_proto_Body_descriptor;
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.Body getDefaultInstanceForType() {
        return com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.getDefaultInstance();
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.Body build() {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.Body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.im.zemel.protoBean.CommonMsgPBOuterClass.Body buildPartial() {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.Body result = new com.im.zemel.protoBean.CommonMsgPBOuterClass.Body(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.im.zemel.protoBean.CommonMsgPBOuterClass.Body) {
          return mergeFrom((com.im.zemel.protoBean.CommonMsgPBOuterClass.Body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.im.zemel.protoBean.CommonMsgPBOuterClass.Body other) {
        if (other == com.im.zemel.protoBean.CommonMsgPBOuterClass.Body.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.im.zemel.protoBean.CommonMsgPBOuterClass.Body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.im.zemel.protoBean.CommonMsgPBOuterClass.Body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.im.zemel.proto.Body)
    }

    // @@protoc_insertion_point(class_scope:com.im.zemel.proto.Body)
    private static final com.im.zemel.protoBean.CommonMsgPBOuterClass.Body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.im.zemel.protoBean.CommonMsgPBOuterClass.Body();
    }

    public static com.im.zemel.protoBean.CommonMsgPBOuterClass.Body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Body>
        PARSER = new com.google.protobuf.AbstractParser<Body>() {
      @java.lang.Override
      public Body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Body> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.im.zemel.protoBean.CommonMsgPBOuterClass.Body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_im_zemel_proto_CommonMsgPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_im_zemel_proto_CommonMsgPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_im_zemel_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_im_zemel_proto_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_im_zemel_proto_Body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_im_zemel_proto_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$com/im/zemel/proto/CommonMsgPB.proto\022\022" +
      "com.im.zemel.proto\"\266\001\n\013CommonMsgPB\022-\n\004ty" +
      "pe\030\001 \002(\0162\037.com.im.zemel.proto.MessageTyp" +
      "e\022\016\n\006fromId\030\002 \001(\005\022\014\n\004toId\030\003 \001(\005\022\017\n\007conte" +
      "nt\030\004 \001(\t\022&\n\004user\030\005 \001(\0132\030.com.im.zemel.pr" +
      "oto.User\022\014\n\004time\030\006 \001(\t\022\023\n\013contentType\030\007 " +
      "\001(\005\"%\n\004User\022\013\n\003uid\030\001 \001(\005\022\020\n\010password\030\002 \001" +
      "(\t\"\006\n\004Body*E\n\013MessageType\022\007\n\003Msg\020\000\022\t\n\005Lo" +
      "gin\020\001\022\r\n\tNewFriend\020\003\022\t\n\005Error\020\004\022\010\n\004Ping\020" +
      "\005B\030\n\026com.im.zemel.protoBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_im_zemel_proto_CommonMsgPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_im_zemel_proto_CommonMsgPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_im_zemel_proto_CommonMsgPB_descriptor,
        new java.lang.String[] { "Type", "FromId", "ToId", "Content", "User", "Time", "ContentType", });
    internal_static_com_im_zemel_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_im_zemel_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_im_zemel_proto_User_descriptor,
        new java.lang.String[] { "Uid", "Password", });
    internal_static_com_im_zemel_proto_Body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_im_zemel_proto_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_im_zemel_proto_Body_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
